name: telegram-notification
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master
      - name: send custom message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }} # user id or channel name secret
          token: ${{ secrets.TELEGRAM_TOKEN }} # token secret
          args: The ${{ github.event_name }} event triggered on ${{ github.repository }} [${{ job.status }}].